name: AWS Lambda Deploy 
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: My first action
        env:
          CERTIFICATE_BASE64: ${{ secrets.SETTINGS_JSON }}
        run: |
          echo-n $JSON_DECODE | base64 --decode > ./config/application.yml

      - name: checkout
        uses: actions/checkout@v3

      - name: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      - name: get-caller-identity is allowed to run on role.
        run: aws sts get-caller-identity

      - name: setup-java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: maven
      - name: Build with Maven
        run: mvn clean install --file pom.xml

      - name: lambda update
        run: |
          # zip -r package.zip ./*
          # aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://package.zip --publish
          cd target
          aws lambda update-function-code --function-name ${{ secrets.FUNCTION_NAME }} --zip-file fileb://lambdatest-aws-package.zip --publish
